title: Jisan's homepage
description: Bookmark this to keep an eye on my project-blog updates!
facebook_url: "https://www.facebook.com/al.takvir.ahmed.jisan/"
email: "ajisan2330152@bsds.uiu.ac.bd"
theme: jekyll-theme-minimal
baseurl: ""
url: "https://jisan002.github.io"

collections:
  posts:
    output: true
