title: Jisan's ThinkLab
description: Bookmark this to keep an eye on my project-blog updates!
minima:
  skin: classic
  background_image: "/assets/images/bg.jpeg"
  
  
baseurl: ""  
url: "https://jisan002.github.io"



defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /:categories/:year/:month/:day/:title.html

